package FundraisingApp;


/**
* FundraisingApp/Fundraising.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fundraising.idl
* 27 October 2014 16:01:40 o'clock GMT
*/

public interface Fundraising extends FundraisingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fundraising
