package FundraisingApp;


/**
* FundraisingApp/FundraisingHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fundraising.idl
* 27 October 2014 16:01:40 o'clock GMT
*/

abstract public class FundraisingHelper
{
  private static String  _id = "IDL:FundraisingApp/Fundraising:1.0";

  public static void insert (org.omg.CORBA.Any a, FundraisingApp.Fundraising that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FundraisingApp.Fundraising extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FundraisingApp.FundraisingHelper.id (), "Fundraising");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FundraisingApp.Fundraising read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FundraisingStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FundraisingApp.Fundraising value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FundraisingApp.Fundraising narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FundraisingApp.Fundraising)
      return (FundraisingApp.Fundraising)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FundraisingApp._FundraisingStub stub = new FundraisingApp._FundraisingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FundraisingApp.Fundraising unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FundraisingApp.Fundraising)
      return (FundraisingApp.Fundraising)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FundraisingApp._FundraisingStub stub = new FundraisingApp._FundraisingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
