package FundraisingApp;


/**
* FundraisingApp/FundraisingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Fundraising.idl
* 27 October 2014 16:01:40 o'clock GMT
*/

public interface FundraisingOperations 
{
  void donate (double amount);
  double getBalance ();
  double getAvgDonation ();
  int getNumberDonors ();
} // interface FundraisingOperations
